/**
 * AWS Solutions Architect Associate (SAA-C03) proof-based labs — Architect Trials.
 * Two labs: VPC with public/private subnets + Multi-AZ RDS demonstration.
 */

import { proofLab, task } from '../authoring-rich';
import type { ProofLab } from '@certquest/types';

const C = 'aws-saa';

export const awsSaaProofLabs: ProofLab[] = [
  proofLab({
    id: 'saa-lab-001',
    certId: C,
    domainId: 'saa-resilient',
    objectiveId: 'saa-obj-iam-advanced',
    title: 'The Two-Tier VPC Trial',
    difficulty: 'intermediate',
    estimatedMinutes: 45,
    xpReward: 110,
    loreNarration:
      'Master Well-Arch sets a blank parchment on the council table. "Build a VPC with two tiers — a public subnet for what the world may touch, a private subnet for what only you may touch. The Trial measures whether ' +
      'you understand routing tables, NAT gateways, and security groups in concert. The Council does not accept \'mostly working.\' Show the IP that traveled through your NAT gateway. Show the connection refused on the database. Two proofs."',
    tools: [
      { name: 'AWS Free Tier account', url: 'https://aws.amazon.com/free/', notes: 'NAT Gateway is NOT free tier — incurs ~$0.045/hour. Delete promptly after lab.' },
      { name: 'AWS Management Console' },
      { name: 'EC2 Key Pair', notes: 'Required for SSH; create or reuse one in your region.' },
    ],
    setup:
      'In your AWS console, choose a region (e.g., us-east-1). You\'ll create one VPC, two subnets (public + private), an Internet Gateway, a NAT Gateway, two route tables, and two t2.micro EC2 instances ' +
      'for testing. Free Tier covers EC2 hours but NOT NAT Gateway — budget about $1 if the lab takes 1–2 hours; delete the NAT Gateway immediately when done.',
    learningObjectives: [
      'Design a VPC with public and private subnet tiers',
      'Configure route tables to direct traffic via IGW (public) vs NAT (private)',
      'Apply security groups to enforce least-network-privilege between tiers',
      'Verify the design by SSH bastion → private host pattern',
      'Recognize NAT Gateway as billable and design with cost awareness',
    ],
    tasks: [
      task('t1',
        'Create a VPC with CIDR 10.20.0.0/16. Inside it, create a public subnet 10.20.1.0/24 and a private subnet 10.20.2.0/24, each in different AZs (e.g., us-east-1a and us-east-1b).',
        'screenshot',
        undefined,
        'Take a screenshot of the VPC dashboard showing both subnets and their CIDR/AZ.',
        false),
      task('t2',
        'Create and attach an Internet Gateway to the VPC. Create a Public Route Table; add a default route 0.0.0.0/0 → IGW; associate with the public subnet. Take a screenshot of the public route table\'s routes tab.',
        'screenshot',
        undefined,
        'Without IGW + the 0.0.0.0/0 route, the "public" subnet cannot reach the internet.',
        false),
      task('t3',
        'Allocate an Elastic IP. Create a NAT Gateway in the public subnet, attached to the EIP. Create a Private Route Table; add 0.0.0.0/0 → NAT Gateway; associate with the private subnet. Note the EIP\'s public IP — you\'ll verify it appears as the egress IP from the private host.',
        'free_response',
        undefined,
        'NAT Gateway must be in a public subnet (it needs IGW reachability). Private subnet routes through it.',
        false),
      task('t4',
        'Launch two t2.micro EC2 instances. Bastion: in the public subnet, with public IP, SG allowing SSH (22) from your IP only. AppHost: in the private subnet, no public IP, SG allowing SSH (22) only from the Bastion\'s SG (security-group reference, not CIDR).',
        'screenshot',
        undefined,
        'SG-to-SG references are the SAA-preferred pattern over IP allowlisting between tiers.',
        false),
      task('t5',
        'SSH to Bastion. From Bastion, SSH to AppHost (use SSH agent forwarding or copy the key). On AppHost, run `curl -s ifconfig.me` (or `curl -s checkip.amazonaws.com`). Paste the IP returned.',
        'output_match',
        'matches NAT Gateway EIP',
        'The egress IP returned should equal the EIP attached to your NAT Gateway. This proves the routing works.',
        false),
      task('t6',
        'From your laptop (NOT the bastion), attempt `ssh ec2-user@<AppHost-private-IP>`. It should fail / time out. Paste the error.',
        'output_match',
        'connection timed out OR no route to host',
        'AppHost is in a private subnet with no public IP. Direct SSH from outside the VPC is impossible — that\'s the point.',
        false),
      task('t7',
        'Cleanup is critical: delete the NAT Gateway FIRST (it\'s the billable item), then release the EIP, terminate the EC2 instances, delete the route tables, subnets, IGW, VPC. Take a screenshot of the VPC dashboard showing the VPC is gone.',
        'screenshot',
        undefined,
        'NAT Gateway billing stops only when the gateway is DELETED, not just when the EIP is released.',
        false),
    ],
    commonMistakes: [
      'Forgetting that NAT Gateway must live in the PUBLIC subnet to reach IGW',
      'Using a CIDR allowlist instead of SG-to-SG references between tiers (the SAA-preferred pattern)',
      'Leaving the NAT Gateway running after the lab — it costs ~$32/month idle',
      'Confusing NAT Gateway (managed, $) with NAT Instance (self-hosted EC2, manageable)',
    ],
    troubleshooting: [
      { symptom: 'Bastion SSH times out', fix: 'Check public subnet route table has 0.0.0.0/0 → IGW, instance SG allows SSH from your IP, NACL is default-allow.' },
      { symptom: 'AppHost cannot reach internet via NAT', fix: 'Private route table missing 0.0.0.0/0 → NAT GW, OR NAT GW is in the private subnet (must be in public).' },
      { symptom: 'Cannot SSH from Bastion to AppHost', fix: 'AppHost SG must reference Bastion\'s SG ID on port 22; both instances must use the same key pair OR you must use agent forwarding.' },
    ],
    sourceRefs: [
      'https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Scenario2.html',
    ],
  }),

  proofLab({
    id: 'saa-lab-002',
    certId: C,
    domainId: 'saa-resilient',
    objectiveId: 'saa-obj-ha',
    title: 'Multi-AZ Failover Demonstration',
    difficulty: 'intermediate',
    estimatedMinutes: 50,
    xpReward: 120,
    loreNarration:
      'Master Well-Arch points at a stone tablet inscribed "RPO < 5 min, RTO < 2 min." "A scribe will tell you they have high availability. The Council requires you to prove it. Today you will provision Multi-AZ RDS, ' +
      'connect to it, force a failover, and measure the disconnection. The Architect Trials accept three artifacts: the Multi-AZ flag, the failover event log, and the disconnection duration."',
    tools: [
      { name: 'AWS Free Tier account', url: 'https://aws.amazon.com/free/', notes: 'RDS Multi-AZ is NOT free tier — uses ~$0.034/hour for db.t3.micro Multi-AZ. Budget ~$2 for a 2-hour lab.' },
      { name: 'AWS Management Console' },
      { name: 'MySQL or PostgreSQL client', notes: 'mysql, psql, or DBeaver. Run from the bastion host (Lab 1) or a free-tier EC2 in the same VPC.' },
    ],
    setup:
      'You need a VPC with at least two private subnets in different AZs (Lab 1 only had one private subnet — for this lab, add a second private subnet in a different AZ). RDS Multi-AZ requires a DB Subnet Group ' +
      'spanning at least two AZs. You\'ll launch a small RDS MySQL instance with Multi-AZ ON, connect from a same-VPC EC2, and force a failover.',
    learningObjectives: [
      'Provision an RDS Multi-AZ deployment',
      'Understand the difference between Multi-AZ standby (sync) and Read Replicas (async)',
      'Trigger a managed failover and observe DNS endpoint behavior',
      'Measure RTO empirically (the actual cutover time)',
      'Recognize that RDS Multi-AZ does not require app-side connection-string changes',
    ],
    tasks: [
      task('t1',
        'In the same VPC from Lab 1 (or a fresh VPC), ensure two private subnets exist in different AZs (us-east-1a and us-east-1b). Create a DB Subnet Group named `cq-saa-dbsg` covering both subnets. Take a screenshot.',
        'screenshot',
        undefined,
        'Multi-AZ requires a DB Subnet Group spanning ≥2 AZs in the VPC.',
        false),
      task('t2',
        'Create an RDS MySQL DB instance: db.t3.micro, "Production" template OR explicitly enable Multi-AZ deployment. Set master username/password. Choose the DB Subnet Group from Task 1. Set the DB SG to allow MySQL (3306) from your bastion\'s SG. Note the Multi-AZ status.',
        'output_match',
        'Multi-AZ: Yes',
        'In the RDS console, confirm "Multi-AZ" reads "Yes" on the DB instance details page after creation completes (~10 min).',
        false),
      task('t3',
        'Note the DB endpoint (e.g., `cq-db.xxx.us-east-1.rds.amazonaws.com`). From your bastion EC2, install mysql client and connect: `mysql -h ENDPOINT -u admin -p`. Run `SELECT @@aurora_version, @@hostname, @@version;` (or just `SELECT @@hostname;`). Note the hostname.',
        'output_match',
        'connection succeeds',
        'You should reach the primary. Note the @@hostname — it identifies which underlying instance you\'re on.',
        false),
      task('t4',
        'In a second terminal (still on bastion), run a tight loop: `while true; do mysql -h ENDPOINT -u admin -pYOURPW -e "SELECT NOW(), @@hostname;" 2>&1 | head -1; sleep 1; done`. Leave it running. This is your "RTO measurement loop."',
        'free_response',
        undefined,
        'You\'ll see a row per second showing the current time and primary hostname.',
        false),
      task('t5',
        'In the RDS console, select the DB instance > Actions > Reboot > check "Reboot with failover" > Confirm. Watch your loop in the other terminal. The connection will fail for some seconds while DNS flips to the standby. Record: (a) timestamp of last successful query before failure, (b) timestamp of first successful query after recovery. Report the difference (RTO).',
        'calculation',
        '~30–120 seconds',
        'Typical Multi-AZ failover RTO is 60–120 seconds. The loop captures the gap; subtract last-success from first-recovery.',
        true),
      task('t6',
        'After failover completes, check @@hostname again. It should be DIFFERENT from Task 3 — confirming you\'re now on what was the standby.',
        'output_match',
        'different hostname than before failover',
        'Same DB endpoint resolves to different physical instance. App didn\'t need to change connection string — that\'s the value of Multi-AZ.',
        false),
      task('t7',
        'Cleanup: in RDS, delete the DB instance (uncheck "create final snapshot" — this is throwaway lab data). Delete the DB Subnet Group. Verify the RDS instance is gone from your console.',
        'screenshot',
        undefined,
        'RDS Multi-AZ continues billing while running. Delete promptly. Final-snapshot option saves $0 if unchecked.',
        false),
    ],
    commonMistakes: [
      'Confusing Multi-AZ with Read Replicas — Multi-AZ does NOT scale reads',
      'Provisioning Multi-AZ on a single-AZ DB Subnet Group — the operation will fail',
      'Forgetting to reboot WITH FAILOVER (just rebooting doesn\'t test the standby)',
      'Leaving the DB running after the lab — Multi-AZ db.t3.micro accrues ~$25/month',
    ],
    troubleshooting: [
      { symptom: 'Cannot connect to DB endpoint', fix: 'Check the DB security group allows MySQL/PostgreSQL port from your bastion\'s SG. Public access is OFF — connect from inside the VPC.' },
      { symptom: 'Failover loop never recovers', fix: 'DNS TTL may be ~60 seconds. Some clients cache DNS — use mysql with explicit endpoint, not a hardcoded IP.' },
      { symptom: 'Cannot enable Multi-AZ during creation', fix: 'You\'re using "Free tier" template. Use "Production" or "Dev/Test" template (will exit free-tier billing).' },
    ],
    sourceRefs: [
      'https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.MultiAZ.html',
    ],
  }),
];
