/**
 * AWS Cloud Practitioner (CLF-C02) proof-based labs — Cloud Village.
 * Two labs: IAM least privilege + S3 lifecycle.
 */

import { proofLab, task } from '../authoring-rich';
import type { ProofLab } from '@certquest/types';

const C = 'aws-ccp';

export const awsCcpProofLabs: ProofLab[] = [
  proofLab({
    id: 'ccp-lab-001',
    certId: C,
    domainId: 'ccp-security',
    objectiveId: 'ccp-obj-iam',
    title: 'The Least-Privilege Doctrine',
    difficulty: 'beginner',
    estimatedMinutes: 35,
    xpReward: 90,
    loreNarration:
      'Sage Nimbus speaks softly. "Every key in Cloud Village opens exactly one door. Not the village gate. Not the temple. Not the library. One door. Today you will craft such a key for a developer who needs to ' +
      'read from one S3 bucket and nothing else. Then you will test it — confirm it opens that bucket, and confirm it opens nothing else. Two proofs. Always two."',
    tools: [
      { name: 'AWS Free Tier account', url: 'https://aws.amazon.com/free/', notes: 'Required. IAM and S3 free-tier-eligible operations are used.' },
      { name: 'AWS Management Console', notes: 'Browser-based admin UI.' },
      { name: 'AWS CLI v2 (optional)', url: 'https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html', notes: 'For verification commands.' },
    ],
    setup:
      'Sign in to the AWS Management Console as your root or admin user. (Lab uses Free Tier — incurs no cost if cleaned up afterward.) Note the AWS region you\'re working in (e.g., us-east-1).',
    learningObjectives: [
      'Create an IAM user with programmatic access',
      'Author a least-privilege JSON policy from scratch',
      'Test that a policy ALLOWS the intended action',
      'Test that a policy DENIES everything else (the harder test)',
      'Clean up IAM resources to avoid security drift',
    ],
    tasks: [
      task('t1',
        'In S3, create a bucket named `cq-iam-lab-<your-initials>-<random-4-digits>`. Create one test object inside (any small text file). Copy the bucket ARN — you\'ll need it.',
        'free_response',
        undefined,
        'Bucket names must be globally unique. The random digits avoid collision.',
        false),
      task('t2',
        'In IAM, create a user named `cq-readonly-user`. Choose "Programmatic access" only (no console password). Do NOT attach any AWS-managed policies.',
        'screenshot',
        undefined,
        'Take a screenshot of the user creation review page showing zero policies attached.',
        false),
      task('t3',
        'Create an inline policy on `cq-readonly-user` granting only s3:GetObject and s3:ListBucket on YOUR specific bucket (use the ARN you noted). Paste the JSON policy here.',
        'free_response',
        undefined,
        'Two statements: one for ListBucket on the bucket ARN, one for GetObject on bucket ARN + "/*".',
        false),
      task('t4',
        'Generate access keys for `cq-readonly-user`. Configure AWS CLI with these keys as a named profile: `aws configure --profile cq-readonly`. Run `aws s3 ls s3://YOUR-BUCKET --profile cq-readonly`. Paste the result.',
        'output_match',
        'object listing succeeds',
        'You should see the test object you uploaded in Task 1.',
        false),
      task('t5',
        'Test the negative case. Run `aws s3 ls --profile cq-readonly` (without specifying the bucket — this lists ALL buckets). Paste the result. (It should fail.)',
        'output_match',
        'AccessDenied',
        'Listing all buckets requires s3:ListAllMyBuckets, which your policy does NOT grant.',
        false),
      task('t6',
        'Test another negative case. Run `aws ec2 describe-instances --profile cq-readonly`. Paste the error.',
        'output_match',
        'UnauthorizedOperation OR AccessDenied',
        'Your policy grants no EC2 permissions, so any EC2 call fails. Proves the deny-by-default principle.',
        false),
      task('t7',
        'Clean up. Delete the user, the access keys, the bucket, and the bucket\'s test object. Confirm by re-running `aws s3 ls` with your admin profile and verifying the bucket is gone.',
        'output_match',
        'bucket no longer listed',
        'Always clean up IAM resources after labs — orphaned users with active keys are the #1 cause of AWS account compromise.',
        false),
    ],
    commonMistakes: [
      'Attaching AmazonS3ReadOnlyAccess instead of writing a custom policy — it grants more than required',
      'Forgetting the trailing "/*" on object-level ARNs (without it, GetObject does not match)',
      'Granting Resource: "*" instead of specific ARN — defeats least privilege',
      'Skipping cleanup, leaving active access keys in your account',
    ],
    troubleshooting: [
      { symptom: 'aws s3 ls succeeds but expected it to fail', fix: 'Check your CLI is using the right profile (--profile cq-readonly). Default profile may have admin perms.' },
      { symptom: 'Inline policy throws "Malformed JSON"', fix: 'Validate the JSON. Common issues: trailing comma, missing quotes around strings, missing Version field.' },
    ],
    sourceRefs: [
      'https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html',
      'https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_examples.html',
    ],
  }),

  proofLab({
    id: 'ccp-lab-002',
    certId: C,
    domainId: 'ccp-billing',
    objectiveId: 'ccp-obj-pricing',
    title: 'The S3 Lifecycle Cascade',
    difficulty: 'beginner',
    estimatedMinutes: 30,
    xpReward: 80,
    loreNarration:
      'Sage Nimbus opens a wooden box of receipts. "The Billing Fog hides cost in two ways: first, by storing rarely-used data in expensive classes; second, by keeping forgotten objects forever. The lifecycle ' +
      'policy is your candle in the fog. Today you will write one — Standard for thirty days, Standard-IA for ninety, Glacier Deep Archive thereafter. Then you will inspect the policy and prove the rules apply."',
    tools: [
      { name: 'AWS Free Tier account', url: 'https://aws.amazon.com/free/', notes: 'Lifecycle rules are free to define; transitions/storage incur normal storage class charges.' },
      { name: 'AWS Management Console' },
      { name: 'AWS CLI v2 (optional)', url: 'https://docs.aws.amazon.com/cli/' },
    ],
    setup:
      'Use a Free Tier AWS account. Create a new S3 bucket dedicated to this lab; you\'ll add a lifecycle policy to it and then delete the bucket when done. Free Tier covers most of the operations.',
    learningObjectives: [
      'Build a multi-stage S3 lifecycle policy from cost-vs-access requirements',
      'Distinguish "transition" actions (move to cheaper class) from "expiration" (delete)',
      'Read a lifecycle policy JSON and predict what will happen to an object on day N',
      'Identify when Glacier Instant vs Flexible vs Deep Archive is appropriate',
    ],
    tasks: [
      task('t1',
        'Create a new S3 bucket `cq-lifecycle-lab-<initials>-<random>`. Upload three small text files (any content). Note the upload date.',
        'screenshot',
        undefined,
        'Three objects in a bucket; record the date.',
        false),
      task('t2',
        'In the bucket\'s Management tab, create a lifecycle rule named `archive-cascade`. Apply to ALL objects in the bucket. Set transitions: Day 30 to Standard-IA; Day 90 to Glacier Deep Archive. Add expiration: Day 2555 (7 years).',
        'screenshot',
        undefined,
        'Take a screenshot of the rule summary showing the three actions.',
        false),
      task('t3',
        'Export the lifecycle policy as JSON. From CLI: `aws s3api get-bucket-lifecycle-configuration --bucket YOUR-BUCKET`. Paste the JSON output.',
        'free_response',
        undefined,
        'The JSON shows the rule structure. Verify it has Transitions[] with both stages and an Expiration field.',
        false),
      task('t4',
        'Predict: an object uploaded today, on day 100, what storage class will it be in? Answer with reasoning.',
        'output_match',
        'Glacier Deep Archive',
        'Day 30: moves to Standard-IA. Day 90: moves to Glacier Deep Archive. Day 100 is past day 90 — Deep Archive.',
        true),
      task('t5',
        'Compare cost. Pull current S3 pricing: Standard ~$0.023/GB-month (us-east-1), Standard-IA ~$0.0125/GB-month, Glacier Deep Archive ~$0.00099/GB-month. For 1 TB stored 1 year under your policy (30 days Standard + 60 days IA + 275 days Deep Archive), what is the approximate annual cost? Show your math.',
        'calculation',
        '~$11–13',
        'Standard: 1 mo × $23 = $23. Standard-IA: 2 mo × $12.5 = $25. Deep Archive: 9 mo × $1 = $9. Total ≈ $57. (Without lifecycle: 12 × $23 = $276 — about 5x more.)',
        true),
      task('t6',
        'Cleanup: delete the bucket\'s lifecycle rule (or just delete the bucket). Confirm via `aws s3api get-bucket-lifecycle-configuration --bucket YOUR-BUCKET` returns an error or empty.',
        'output_match',
        'NoSuchLifecycleConfiguration OR bucket deleted',
        'Empty bucket can be deleted from the console. Lifecycle rules are billing-free to remove.',
        false),
    ],
    commonMistakes: [
      'Setting transition days that violate AWS minimums (e.g., Standard-IA requires ≥30 days)',
      'Forgetting that Glacier Deep Archive has a 12-hour retrieval delay',
      'Using "Glacier Instant" thinking it\'s cheapest — it\'s the most-expensive Glacier class',
      'Configuring expiration without confirming with the team — premature deletion of compliance data',
    ],
    troubleshooting: [
      { symptom: 'Lifecycle rule rejected with InvalidArgument', fix: 'Check minimum days: Standard-IA = 30, Glacier Flexible = 90 days minimum after Standard-IA.' },
      { symptom: 'Want to test transitions immediately', fix: 'You can\'t — AWS evaluates lifecycle rules once daily. Use an existing object date or wait.' },
    ],
    sourceRefs: [
      'https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lifecycle-mgmt.html',
      'https://aws.amazon.com/s3/pricing/',
    ],
  }),
];
